import type { Metadata } from "next";
import { LidarHeightLab, LidarMetricChooser, LidarProfileLab } from "@/app/components/lidar-field-lab-interactions";
import { JsonLd, SeoBreadcrumbs, SeoFooter, SeoHeader } from "@/app/components/seo-navigation";
import { lidarFieldLabPath, lidarFieldLabSources, lidarWorkflowSteps } from "@/lib/lidar-field-lab";
import { creatorReference } from "@/lib/professional-identity";
import { academyAssetUrl, academyHref, academyUrl } from "@/lib/site-paths";

const url = academyUrl(lidarFieldLabPath);
export const metadata: Metadata = { title: "Field Lab 09 · LiDAR Canopy Structure | Remote Sensing Scientist Academy", description: "Audit a LiDAR point cloud, validate ground classification, normalize height and create defensible structural metrics and canopy-height products.", alternates: { canonical: url }, openGraph: { title: "Field Lab 09 · LiDAR Canopy Structure", description: "Point cloud to validated structural evidence.", type: "article", url, images: [{ url: academyAssetUrl("/og.png"), width: 1536, height: 1024, alt: "Remote Sensing Scientist Academy" }] } };

export default function LidarFieldLabPage() {
  return <><JsonLd value={{ "@context": "https://schema.org", "@type": "LearningResource", name: "Field Lab 09 · LiDAR Canopy Structure", description: metadata.description, url, learningResourceType: "Field lab", educationalUse: "instruction", creator: creatorReference() }} /><SeoHeader current="field-labs" /><main className="lidar-field-lab" id="main-content"><SeoBreadcrumbs items={[{ label: "Academy", href: academyHref("/") }, { label: "Field Labs", href: academyHref("/field-labs/") }, { label: "LiDAR canopy structure" }]} />
    <header className="lidar-lab-hero"><div><p className="section-kicker">Field Lab 09 · LiDAR</p><h1>Turn laser returns into structural evidence</h1><p>Audit a three-dimensional point cloud, establish a defensible terrain surface, normalize height, derive canopy metrics and validate the final quantity at the support where it will be interpreted.</p><div><a href="#lidar-workflow">Start the workflow</a><a href={academyHref("/module-2/lidar-and-point-clouds/")}>Review LiDAR fundamentals</a></div></div><aside><span>THE DERIVATION</span><p><b>range returns</b><i>→</i><b>classified points</b><i>→</i><b>terrain</b><i>→</i><b>height above ground</b><i>→</i><b>structural metric</b></p></aside></header>
    <section className="lidar-scope"><strong>Lab evidence boundary</strong><p>The included point table is a tiny synthetic teaching fixture, not a real LiDAR acquisition and not evidence from the 2024 Estonian UAV campaign. Field Lab 07 uses photogrammetric structure; photogrammetric point cloud ≠ LiDAR point cloud.</p></section>
    <section className="lidar-observation"><div><p className="section-kicker">What the instrument contributes</p><h2>Discrete three-dimensional samples—not a finished canopy surface</h2></div><div className="lidar-pulse-diagram" role="img" aria-label="Laser pulse produces several returns before reaching a ground return"><span>airborne laser</span><i /><b className="return-one">1 · upper vegetation</b><b className="return-two">2 · lower vegetation</b><b className="return-three">3 · ground</b><em>travel time → range</em></div><aside><article><b>OBSERVED / RECORDED</b><p>x, y, z, return attributes, intensity and acquisition metadata.</p></article><article><b>INTERPRETED / DERIVED</b><p>classification, DTM, DSM, normalized height, CHM and plot/cell metrics.</p></article></aside></section>
    <LidarHeightLab /><LidarProfileLab />
    <section className="lidar-workflow" id="lidar-workflow" aria-labelledby="lidar-workflow-title"><header><p className="section-kicker">End-to-end procedure</p><h2 id="lidar-workflow-title">Question → points → ground → height → validation</h2><p>Each step has a stop condition. Do not make downstream surfaces prettier when the upstream point evidence is weak.</p></header><nav aria-label="LiDAR workflow">{lidarWorkflowSteps.map((step) => <a href={`#lidar-step-${step.number}`} key={step.number}><span>{step.number}</span>{step.phase}</a>)}</nav><div>{lidarWorkflowSteps.map((step) => <article id={`lidar-step-${step.number}`} key={step.number}><header><span>{step.number} · {step.phase}</span><h3>{step.title}</h3><p>{step.what}</p></header><section><div><h4>ACTION</h4><ol>{step.action.map((item) => <li key={item}>{item}</li>)}</ol></div><div><h4>INPUT</h4><ul>{step.input.map((item) => <li key={item}>{item}</li>)}</ul><h4>OUTPUT</h4><ul>{step.output.map((item) => <li key={item}>{item}</li>)}</ul></div><div><h4>CHECK</h4><ul>{step.check.map((item) => <li key={item}>{item}</li>)}</ul><aside><b>IF THIS FAILS</b><p>{step.failure}</p></aside></div></section></article>)}</div></section>
    <LidarMetricChooser />
    <section className="lidar-products"><header><p className="section-kicker">Required handoff</p><h2>Keep measurement, model and uncertainty side by side</h2></header><div><article><span>POINTS</span><h3>Accepted + flagged LAZ</h3><p>Source attributes, classifications, flags, CRS and vertical reference remain traceable.</p></article><article><span>TERRAIN</span><h3>DTM + void mask</h3><p>Bare-earth estimate with interpolation method and independent checkpoint accuracy.</p></article><article><span>STRUCTURE</span><h3>CHM + metrics</h3><p>Derived height products with exact cell/plot support, included classes and minimum count.</p></article><article><span>EVIDENCE</span><h3>Density + validation</h3><p>Coverage, residuals, sensitivity, applicability and supported non-claims.</p></article></div><aside><b>Can support:</b> a validated LiDAR-derived structural metric at the stated support.<br /><b>Cannot automatically support:</b> species identity, biomass, habitat quality or ecological cause.</aside></section>
    <section className="lidar-downloads"><div><p className="section-kicker">Workstation pack</p><h2>Download the point audit</h2><p>Keep the source-status and deliberate-condition fields in every submission.</p></div><div><a href={academyAssetUrl("/lesson-resources/module-2/satellite-eo/lidar_point_samples.csv")} download>Synthetic LiDAR point samples · CSV</a><a href={academyAssetUrl("/field-labs/lidar-canopy-structure/lidar-evidence-checklist.md")} download>LiDAR evidence checklist · Markdown</a></div></section>
    <section className="lidar-references"><p className="section-kicker">Authoritative references</p><h2>Standards and methods to keep beside the workflow</h2><ul><li><a href={lidarFieldLabSources.usgsSpecification} target="_blank" rel="noopener noreferrer">USGS LiDAR Base Specification, current online edition ↗</a></li><li><a href={lidarFieldLabSources.usgsProcessing} target="_blank" rel="noopener noreferrer">USGS processing, classification and accuracy requirements ↗</a></li><li><a href={lidarFieldLabSources.usgsDeliverables} target="_blank" rel="noopener noreferrer">USGS point-cloud and metadata deliverables ↗</a></li><li><a href={lidarFieldLabSources.neonChm} target="_blank" rel="noopener noreferrer">NSF NEON canopy-height model tutorial ↗</a></li><li><a href={lidarFieldLabSources.pdalHag} target="_blank" rel="noopener noreferrer">PDAL height-above-ground method documentation ↗</a></li></ul></section>
  </main><SeoFooter /></>;
}
