export const lidarFieldLabPath = "/field-labs/lidar-canopy-structure/";

export const lidarFieldLabSources = {
  usgsSpecification: "https://www.usgs.gov/ngp-standards-and-specifications/lidar-base-specification-online",
  usgsProcessing: "https://www.usgs.gov/ngp-standards-and-specifications/lidar-base-specification-data-processing-and-handling-requirements",
  usgsDeliverables: "https://www.usgs.gov/ngp-standards-and-specifications/lidar-base-specification-deliverables",
  neonChm: "https://www.neonscience.org/resources/learning-hub/tutorials/create-chm-rasters-r",
  pdalHag: "https://pdal.io/en/stable/stages/filters.hag_delaunay.html",
} as const;

export const lidarWorkflowSteps = [
  { number: "01", phase: "QUESTION", title: "Define the structural quantity and support", what: "Choose whether the deliverable is a point metric, terrain model, surface model, canopy-height raster or plot summary.", action: ["State the biological or terrain question.", "Define horizontal support and vertical reference.", "Name the field quantity, if any, used for validation.", "Predeclare places where returns may be absent or unreliable."], input: ["Scientific question", "AOI", "Target support", "Validation plan"], output: ["Measurement statement", "Support specification", "Non-claims"], check: ["The target is not simply ‘LiDAR height’.", "The support matches the intended ecological comparison."], failure: "The requested product, support or vertical reference is undefined." },
  { number: "02", phase: "INVENTORY", title: "Read the point-cloud contract before the points", what: "Audit the LAS/LAZ header, collection report and tile inventory.", action: ["Record file version and point format.", "Verify horizontal and vertical CRS, units and datum/geoid information.", "Record acquisition date, sensor, nominal pulse spacing or density and classification scheme.", "Inventory tiles, extents, overlaps and missing files."], input: ["LAS/LAZ files", "Metadata", "Collection report", "Tile index"], output: ["Point-cloud inventory", "CRS/units record", "Coverage map"], check: ["Coordinates fall in a plausible range.", "Vertical units and reference are explicit.", "Tile count matches the index."], failure: "The vertical reference, units or source coverage cannot be established." },
  { number: "03", phase: "POINT QA", title: "Inspect density, coverage and flightline consistency", what: "Assess whether the three-dimensional sampling supports the intended product.", action: ["Map point count or density by cell.", "Separate zero-density gaps from water or masked areas.", "Inspect scan angle and source/flightline identifiers.", "Examine overlap areas for vertical disagreement."], input: ["Source points", "AOI", "Flightline/source IDs"], output: ["Density raster", "Gap mask", "Overlap QA"], check: ["Density is reported as a distribution, not one project-wide average.", "Striping, gaps and edge effects are investigated."], failure: "Coverage gaps or interswath offsets undermine the requested support." },
  { number: "04", phase: "CLEAN", title: "Flag noise without erasing real structure", what: "Identify impossible or isolated returns and preserve the decision trail.", action: ["Inspect elevation distributions and vertical profiles.", "Apply documented range, isolation or neighborhood checks.", "Use classification/withheld flags rather than deleting source points.", "Review bridges, wires, birds and high vegetation before calling them noise."], input: ["Point cloud", "Existing flags/classes", "Neighborhood parameters"], output: ["Flagged working points", "Outlier report", "Unchanged source copy"], check: ["Every filter parameter is recorded.", "Removed/withheld points can be recovered.", "Tall valid structures were not clipped by a global maximum."], failure: "An automated filter removes plausible canopy or terrain features without review." },
  { number: "05", phase: "CLASSIFY", title: "Audit ground classification", what: "Establish which returns support the terrain surface.", action: ["Inspect ground and non-ground classes in cross-section.", "Check slopes, banks, low vegetation, buildings and water edges.", "Correct or flag systematic errors.", "Keep return number and classification conceptually separate."], input: ["Flagged points", "Classification codes", "Reference terrain context"], output: ["Accepted ground subset", "Classification QA map", "Correction log"], check: ["Ground points form a plausible surface.", "Vegetation has not been absorbed into ground.", "First/last return is not treated as a land-cover class."], failure: "Ground classification is inconsistent enough to bias the DTM." },
  { number: "06", phase: "TERRAIN", title: "Interpolate and validate the DTM", what: "Estimate bare-earth elevation from accepted ground points.", action: ["Choose cell size from point spacing, terrain complexity and purpose.", "Interpolate ground returns with a documented method.", "Retain void and extrapolation masks.", "Compare the DTM with independent open-ground checkpoints."], input: ["Accepted ground points", "Grid definition", "Checkpoints"], output: ["DTM", "Interpolation/void mask", "Vertical-accuracy report"], check: ["RMSE and signed bias are reported with sample count.", "Terrain edges and sparse areas are reviewed."], failure: "The DTM fails the stated accuracy need or hides unsupported interpolation." },
  { number: "07", phase: "NORMALIZE", title: "Calculate height above ground", what: "Transform absolute elevation into local structural height.", action: ["Interpolate ground elevation at each accepted point.", "Calculate height_above_ground = z − ground_z.", "Inspect negative and implausibly high normalized values.", "Keep absolute z and normalized height as separate attributes."], input: ["Accepted points", "Validated terrain surface"], output: ["Height-normalized point cloud", "Normalization QA table"], check: ["Ground returns cluster near zero.", "Negative heights are explained or flagged.", "No vertical datum conversion is hidden in the subtraction."], failure: "Normalization creates spatial patterns tied to DTM error rather than structure." },
  { number: "08", phase: "METRICS", title: "Derive structural metrics with explicit support", what: "Summarise the normalized point distribution without confusing samples and surfaces.", action: ["Choose cell or plot support before calculation.", "Calculate count, maximum, percentiles and cover-above-threshold only where meaningful.", "Record minimum point count and empty-cell behavior.", "Create DSM/CHM with a documented gridding method when required."], input: ["Normalized points", "Grid or plot polygons", "Metric definitions"], output: ["Structural-metric table", "CHM or DSM where justified", "Support mask"], check: ["Metric units and denominator are explicit.", "Outlier sensitivity is tested.", "CHM = surface estimate − terrain estimate is labelled derived."], failure: "Cells with sparse or unrepresentative returns are reported as confident structure." },
  { number: "09", phase: "VALIDATE", title: "Validate the derived structure, not only the source cloud", what: "Compare the final metric with independent observations at compatible support.", action: ["Match field and LiDAR acquisition timing as closely as the claim requires.", "Align field locations and plot footprints.", "Compare height metrics with field measurements using bias, error and scatter.", "Stratify residuals by vegetation structure and point density when possible."], input: ["Held-out field measurements", "Derived metrics", "Support and timing metadata"], output: ["Validation table", "Residual plots", "Applicability statement"], check: ["Field height protocol and LiDAR metric describe compatible quantities.", "Validation plots were not used to tune filters."], failure: "The field and LiDAR measurements differ in timing, footprint or definition without qualification." },
  { number: "10", phase: "HANDOFF", title: "Package points, surfaces and evidence separately", what: "Export an analysis-ready structural evidence package.", action: ["Export accepted/flagged LAZ, DTM, CHM and metrics in open formats.", "Save CRS, vertical reference, grid, filter, classification and interpolation records.", "Include density, void, accuracy and applicability layers.", "Write supported claims and explicit non-claims."], input: ["Accepted points", "Derived surfaces/metrics", "QA and validation records"], output: ["LAZ point package", "GeoTIFF/COG rasters", "Metric table", "Manifest and report"], check: ["Every raster aligns to the declared grid.", "Point and raster products retain units and vertical reference.", "Files open outside the production software."], failure: "A user cannot trace a canopy-height value back to source points, ground model and processing decisions." },
] as const;

export const lidarProfilePoints = [
  { id: "P015", z: 1.84, height: 0, classification: "ground", returnText: "2 of 2", valid: true },
  { id: "P016", z: 2.55, height: 0.71, classification: "vegetation", returnText: "1 of 2", valid: true },
  { id: "P017", z: 12.4, height: 10.56, classification: "unclassified", returnText: "1 of 1", valid: false },
  { id: "P018", z: 2.47, height: 0.63, classification: "vegetation", returnText: "1 of 1", valid: true },
] as const;
