export const uavFieldLabPath = "/field-labs/uav-coastal-wetlands/";
export const droneLabPath = "/field-labs/uav-coastal-wetlands/drone-lab/";

export const uavSources = {
  ebee: "https://www.sensefly.com/drones/ebee-x/",
  sequoia: "https://www.parrot.com/assets/s3fs-public/2021-09/sequoia-userguide-en-fr-es-de-it-pt-ar-zn-zh-jp-ko_1.pdf",
  duetT: "https://ageagle.com/wp-content/uploads/2022/08/Camera-Collection-AgEagle-2022-DIGITAL-1.pdf",
  pix4dSteps: "https://support.pix4d.com/hc/en-us/articles/115002472186",
  pix4dProcess: "https://support.pix4d.com/hc/en-us/articles/202557519",
  pix4dThermal: "https://support.pix4d.com/hc/en-us/articles/360000173463",
  trimbleExport: "https://help.fieldsystems.trimble.com/trimble-access/2023.00/en/Job-export-data.htm",
  epsg3301: "https://epsg.org/crs_3301/Estonian-Coordinate-System-of-1997.html",
} as const;

export const scientificPipeline = [
  "Ecological question",
  "Sensor choice",
  "Flight design",
  "Raw imagery",
  "Positioning",
  "PPK / GCP",
  "Photogrammetry",
  "Radiometry",
  "RGB / multispectral / thermal",
  "Reflectance bands",
  "Vegetation indices",
  "DSM",
  "Quality control",
  "Ecological interpretation",
  "Analysis-ready data",
] as const;

export type UavTutorialPhase = "PLAN" | "ACQUIRE" | "POSITION" | "RECONSTRUCT" | "PRODUCTS" | "HANDOFF";

export type UavTutorialStep = {
  number: string;
  phase: UavTutorialPhase;
  title: string;
  what: string;
  action: readonly string[];
  where: string;
  why: string;
  input: readonly string[];
  output: readonly string[];
  check: readonly string[];
  failure: string;
  next: string;
  reference?: string;
};

export const uavTutorialSteps: UavTutorialStep[] = [
  {
    number: "01", phase: "PLAN", title: "Plan the mission from the ecological question",
    what: "Turn the research question into a flight specification before opening the mission planner.",
    action: ["Name the ecological response and the field observation that represents it.", "Draw the site boundary and identify the 1 m² plot support.", "Choose the required products, sensor, GSD, altitude and overlap as one connected decision."],
    where: "Project brief + GIS map; then the mission-planning worksheet.",
    why: "Altitude and overlap are not defaults to copy. They determine coverage, image geometry, processing load and whether the raster support can answer the question.",
    input: ["Research question", "Site boundary", "Field-plot design", "Required raster products"],
    output: ["Mission specification", "Sensor choice", "Target GSD and overlap", "Explicit non-claims"],
    check: ["The requested product can support the ecological response.", "The boundary includes safe operational margin.", "GSD is reported separately from effective spatial resolution."],
    failure: "Stop and revise the question or product list. Do not compensate for an unclear objective by collecting more imagery.",
    next: "Prepare the site, control and field-to-image links.", reference: "reference-sensors",
  },
  {
    number: "02", phase: "PLAN", title: "Prepare the field site and control plan",
    what: "Make the mission physically and spatially observable before the aircraft arrives.",
    action: ["Confirm the approved operating area, take-off/landing area and current weather constraints.", "Verify plot identifiers and geometry used later for raster extraction.", "Plan visible, well-distributed control/check targets where the approved survey design uses them."],
    where: "Field plan, site map and approved flight documentation.",
    why: "A precise orthomosaic cannot repair missing plot identities, unsafe operations or control concentrated in one corner.",
    input: ["Approved mission specification", "Plot and site map", "Control/check-point plan", "Current operational constraints"],
    output: ["Field-readiness record", "Confirmed plot/control identifiers", "Accepted launch/landing plan"],
    check: ["SampleID remains consistent across field and spatial records.", "Control is identifiable and spatially distributed.", "The plan follows current organizational and manufacturer safety procedures."],
    failure: "Do not launch if permissions, site identity, weather limits, control visibility or safe recovery space are unresolved.",
    next: "Translate the approved specification into an eMotion mission.", reference: "reference-geometry",
  },
  {
    number: "03", phase: "PLAN", title: "Build and review the mission in eMotion",
    what: "Convert the approved flight specification into a camera-aware mapping mission.",
    action: ["Create/select the correct site mission and payload.", "Set the planned mapping extent, altitude and longitudinal/lateral overlap.", "Review predicted coverage, GSD, flight duration, battery/endurance and recovery area."],
    where: "eMotion mission-planning workspace.",
    why: "The mission planner links aircraft performance, terrain, camera footprint and image overlap before data are collected.",
    input: ["Site boundary", "Payload", "Altitude/GSD target", "Overlap target", "Operational limits"],
    output: ["Reviewed eMotion mission", "Predicted image footprints", "Recorded planned settings"],
    check: ["Correct site and payload are selected.", "For the 2024 reference: Sequoia 106–109 m AGL with 80/75 overlap; RGB 119–125 m AGL with 85–88/80–86 overlap.", "Coverage includes field plots and control."],
    failure: "Return to mission planning when the predicted coverage, endurance, terrain clearance or landing geometry is unacceptable.",
    next: "Run the approved pre-flight procedure and acquire the mission.", reference: "reference-flight",
  },
  {
    number: "04", phase: "ACQUIRE", title: "Fly and monitor the approved mission",
    what: "Acquire overlapping imagery and flight logs without silently changing the scientific design.",
    action: ["Use the current approved eBee X pre-flight, launch, monitoring and recovery procedure.", "Confirm the correct payload and mission before flight.", "Record departures from the planned mission, illumination, wind or coverage."],
    where: "Field site + eMotion flight-monitoring view.",
    why: "Processing quality depends on what actually happened, not only on the planned settings.",
    input: ["Approved eMotion mission", "Prepared eBee X and payload", "Field-readiness record"],
    output: ["Raw camera images", "Aircraft/mission logs", "Field deviation notes"],
    check: ["The completed flight corresponds to the intended site/date.", "Coverage and image acquisition appear complete.", "Any interruption or deviation is recorded."],
    failure: "Do not invent a launch or electrical sequence from this tutorial. Follow the current authorized hardware procedure and stop when the aircraft, payload or mission state is uncertain.",
    next: "Preserve and inventory the raw evidence before processing.", reference: "reference-flight",
  },
  {
    number: "05", phase: "ACQUIRE", title: "Retrieve, copy and preserve the raw data",
    what: "Separate source media, immutable raw copies and working folders.",
    action: ["Retrieve camera media and the required aircraft logs using the approved eBee X procedure.", "Copy RGB, multispectral, thermal, log and GNSS files into sensor-specific raw folders.", "Compare counts and sizes, then preserve the raw copy unchanged."],
    where: "Camera SD/internal log access → project drive /raw directory.",
    why: "Processing from the SD card risks loss and makes recovery or audit impossible.",
    input: ["Camera media", "Aircraft logs", "GNSS files", "Field notes"],
    output: ["Verified raw-data inventory", "Read-only source copy", "Separate processing workspace"],
    check: ["Site/date/payload agree across media and notes.", "File counts and sizes reconcile.", "Raw and processing directories are distinct."],
    failure: "Stop if files are missing, unreadable, mixed between missions or being processed directly from source media.",
    next: "Match the correct log, image folder and time interval.",
  },
  {
    number: "06", phase: "POSITION", title: "Match mission logs, images and time",
    what: "Identify one mission unambiguously and associate its image captures with the flight record.",
    action: ["Open eMotion Postflight and select the correct flight log.", "Verify site, date, start/end time and time basis.", "Select the matching camera-image folder and inspect the association count."],
    where: "eMotion → Postflight / Flight Data Manager.",
    why: "Image-to-log association supplies capture positions; it is different from Pix4D feature matching between photographs.",
    input: ["Copied flight log", "Matching image folder", "Field mission record"],
    output: ["One identified mission", "Images associated with log events", "Verified flight interval"],
    check: ["For July 2024, Estonia local time was UTC+3; verify rather than applying this seasonally forever.", "The image count is expected and matching is unique.", "The RINEX request interval will cover the flight plus margin."],
    failure: "Do not continue when site/date disagree, the time zone is ambiguous or images cannot be uniquely matched.",
    next: "Load reference observations and solve PPK.", reference: "reference-geometry",
  },
  {
    number: "07", phase: "POSITION", title: "Process PPK with overlapping RINEX data",
    what: "Improve camera geotags by combining UAV rover and reference-station GNSS observations after flight.",
    action: ["Obtain approved observation/navigation files for a reference station and interval covering the mission.", "Load the RINEX data and process PPK.", "Inspect fix status, base position, time overlap and the reported change in uncertainty."],
    where: "eMotion Postflight → PPK/base-station workflow.",
    why: "PPK corrects the camera-position evidence used by photogrammetry; it does not guarantee final map accuracy.",
    input: ["UAV GNSS observations", "Reference-station RINEX", "Verified mission time", "Base metadata"],
    output: ["PPK solution", "Corrected camera geotags", "Positioning QA record"],
    check: ["Reference and rover observations overlap completely.", "The correct base position and antenna metadata are used.", "The manual example changes ≈0.806 m to ≈0.049 m; treat it as an example, not a promise."],
    failure: "Block the mission when the base, time overlap, fix status or solution-quality evidence is wrong or unknown.",
    next: "Preserve corrected geotags and prepare the surveyed-control branch.", reference: "reference-geometry",
  },
  {
    number: "08", phase: "POSITION", title: "Export and audit Trimble GCP data",
    what: "Move surveyed control into a documented interchange file without losing identity, units or CRS.",
    action: ["Open the approved Trimble Access job and choose Export.", "Select the required points and comma-delimited CSV/TXT format.", "Inspect point names, coordinate fields/order, elevation, delimiter, units and CRS before transfer."],
    where: "Trimble Access → Job → Export, then controlled transfer storage.",
    why: "A GCP file is useful only when the coordinates and the physical targets still refer to the same points.",
    input: ["Approved survey job", "Selected control/check points", "Verified export definition"],
    output: ["Audited GCP CSV/TXT", "Recorded export schema", "Controlled transfer copy"],
    check: ["Horizontal CRS is Estonian Coordinate System of 1997 (EPSG:3301).", "Column order and metre units are explicit.", "Internal project/job names are not treated as reusable instructions."],
    failure: "Stop when the job, point role, schema, coordinate order, units or vertical reference is unverified.",
    next: "Create the Pix4D project with corrected imagery and declared coordinate systems.", reference: "reference-geometry",
  },
  {
    number: "09", phase: "RECONSTRUCT", title: "Create the Pix4D project correctly",
    what: "Start a camera-aware reconstruction using the intended corrected imagery and spatial reference.",
    action: ["Create a project outside the raw archive and add all required corrected images.", "For Duet T, include RGB and thermal images and verify groups/camera models.", "Set the output/GCP horizontal CRS to EPSG:3301 for this study."],
    where: "PIX4Dmapper → New Project → Image Properties and coordinate-system settings.",
    why: "Wrong camera grouping, geotags or CRS can produce a completed but spatially meaningless model.",
    input: ["Corrected images", "Camera/geotag metadata", "EPSG:3301 control data", "Processing workspace"],
    output: ["Configured Pix4D project", "Verified image groups", "Declared output/GCP CRS"],
    check: ["Image counts and camera models are plausible.", "RGB and thermal groups are distinguishable.", "Full CRS name, code, units, coordinate order and vertical reference status are recorded."],
    failure: "Do not rely on auto-detected CRS or a similar-looking camera model. Correct the project before processing.",
    next: "Run only Initial Processing to establish camera geometry.", reference: "reference-geometry",
  },
  {
    number: "10", phase: "RECONSTRUCT", title: "Run Initial Processing only",
    what: "Build the initial camera network before dense reconstruction or final rasters.",
    action: ["Keep Initial Processing checked.", "Uncheck Point Cloud and Mesh.", "Uncheck DSM, Orthomosaic and Index, then start step 1."],
    where: "PIX4Dmapper → Processing Options / Start Processing.",
    why: "Feature matching, camera orientation and bundle adjustment must be inspectable before control is marked and expensive products are generated.",
    input: ["Configured Pix4D project", "Overlapping images", "Corrected geotags"],
    output: ["Calibrated images", "Automatic tie points", "Sparse reconstruction", "Initial Quality Report"],
    check: ["Only step 1 ran.", "Images calibrate in one defensible block.", "No matching warning is ignored."],
    failure: "Investigate weak calibration, unexplained blocks, bad overlap or incorrect imagery before proceeding.",
    next: "Read the initial Quality Report before importing control.", reference: "reference-photogrammetry",
  },
  {
    number: "11", phase: "RECONSTRUCT", title: "Read the initial Quality Report",
    what: "Decide whether the unconstrained camera geometry is good enough to continue.",
    action: ["Review calibration and matching summaries.", "Inspect initial positions, blocks, overlap and warnings.", "Record an accept/block decision and the evidence behind it."],
    where: "PIX4Dmapper → Quality Report and rayCloud/map inspection.",
    why: "Software completion only confirms execution; it does not confirm scientific validity.",
    input: ["Initial Quality Report", "Sparse reconstruction", "Image/position summary"],
    output: ["Initial-geometry QA decision", "Issue list", "Accepted state for control work"],
    check: ["Calibrated-image fraction and block structure are sensible.", "Achieved overlap covers the analysis area.", "Warnings have explanations or corrective actions."],
    failure: "Return to images, mission association, camera settings or initial processing; do not hide a weak camera network with GCPs.",
    next: "Import the audited control file.", reference: "reference-photogrammetry",
  },
  {
    number: "12", phase: "RECONSTRUCT", title: "Import GCPs with explicit coordinate mapping",
    what: "Declare surveyed control points and map their CSV columns deliberately.",
    action: ["Open GCP/MTP Manager and confirm EPSG:3301.", "Import the audited CSV/TXT and map point ID, X, Y and Z according to its recorded schema.", "Plot and inspect all imported points."],
    where: "PIX4Dmapper → Project → GCP/MTP Manager → Import GCPs.",
    why: "Import creates control records; it does not prove that the CRS, column order or image target is correct.",
    input: ["Audited GCP file", "Recorded schema", "Verified horizontal CRS"],
    output: ["Imported control-point table", "Plausibly located point set"],
    check: ["Point IDs are intact.", "X/Y/Z order and metre units match the export.", "Points lie inside/around the mission and elevations are plausible."],
    failure: "Remove/correct the import when points are displaced or the coordinate/vertical reference is ambiguous.",
    next: "Identify the same physical GCP target across overlapping images.", reference: "reference-geometry",
  },
  {
    number: "13", phase: "RECONSTRUCT", title: "Manually mark every accepted GCP",
    what: "Measure the exact surveyed target in multiple overlapping camera views.",
    action: ["Select one GCP and find its physical target in suitable images.", "Zoom and mark the same point precisely across well-distributed views.", "Repeat for every accepted GCP while watching reprojection feedback."],
    where: "PIX4Dmapper → GCP/MTP Manager or rayCloud image views.",
    why: "Each click is an image measurement constraining the bundle. Inaccurate or inconsistent marking can degrade the solution.",
    input: ["Imported GCP coordinates", "Initial camera geometry", "Images containing each target"],
    output: ["Multi-image GCP observations", "Marking/reprojection evidence"],
    check: ["The target identity is unambiguous.", "Marks refer to the same physical point.", "Image geometry and spatial distribution are adequate."],
    failure: "Reject or defer obscured/ambiguous targets; never force a mark to increase the count.",
    next: "Reoptimize the bundle using the accepted constraints.", reference: "reference-photogrammetry",
  },
  {
    number: "14", phase: "RECONSTRUCT", title: "Reoptimize and audit the controlled solution",
    what: "Update camera parameters with GCP measurements, then inspect what changed.",
    action: ["Choose Process → Reoptimize.", "Review residuals, camera geometry, calibration and block structure.", "Correct suspicious marks and repeat until the solution is defensible."],
    where: "PIX4Dmapper → Process → Reoptimize; then GCP/MTP Manager and Quality Report.",
    why: "Reoptimization integrates manual control into the bundle adjustment; it is not merely another matching command.",
    input: ["Initial reconstruction", "Accepted GCP marks", "Declared coordinate systems"],
    output: ["Controlled optimized reconstruction", "Residual audit", "Accepted geometry state"],
    check: ["No unexplained residual outlier remains.", "Control covers the project spatially.", "Fitted GCP residuals are not presented as independent check-point accuracy."],
    failure: "Correct the point, mark, CRS or vertical-reference problem and reoptimize again; block dense processing while geometry is unresolved.",
    next: "Generate the dense point cloud from the accepted camera model.", reference: "reference-photogrammetry",
  },
  {
    number: "15", phase: "RECONSTRUCT", title: "Generate and inspect the dense point cloud",
    what: "Reconstruct dense 3-D surface samples from accepted overlapping-image geometry.",
    action: ["Uncheck Initial Processing and enable Point Cloud and Mesh.", "Choose Low/Fast for diagnostic work or Optimal when purpose/resources justify it.", "Run the stage and inspect noise, holes and surface coherence."],
    where: "PIX4Dmapper → Processing Options → Point Cloud and Mesh.",
    why: "The dense cloud supplies surface geometry for DSM production; more points do not automatically mean more positional accuracy.",
    input: ["Accepted optimized cameras", "Calibrated overlapping images", "Documented density setting"],
    output: ["Dense point cloud", "Point-cloud QA record"],
    check: ["Vegetation/water edges and low-texture areas are inspected.", "Noise and gaps are documented.", "Density choice matches the product purpose."],
    failure: "Return to camera geometry, masks or density settings when holes/noise undermine the required surface.",
    next: "Rasterize the accepted visible surface into a DSM.", reference: "reference-products",
  },
  {
    number: "16", phase: "PRODUCTS", title: "Generate and verify the DSM",
    what: "Create a gridded elevation model of the visible upper surface.",
    action: ["Enable DSM generation from the accepted reconstruction.", "Set/record output grid, resolution, interpolation and NoData choices.", "Open the DSM independently and inspect its surface."],
    where: "PIX4Dmapper → DSM, Orthomosaic and Index options; then GIS QA.",
    why: "The DSM supports orthorectification and structural predictors, but it includes vegetation and objects rather than bare earth.",
    input: ["Accepted dense cloud", "Output CRS", "Grid/resolution settings"],
    output: ["DSM raster", "DSM metadata", "Surface QA notes"],
    check: ["EPSG:3301 and metre units are present.", "NoData, spikes, pits and water artefacts are understood.", "DSM is never labelled DEM without a terrain model."],
    failure: "Do not calculate height or orthorectify from a DSM with unexplained artefacts or unknown vertical reference.",
    next: "Use the accepted geometry to create the RGB orthomosaic.", reference: "reference-products",
  },
  {
    number: "17", phase: "PRODUCTS", title: "Create the RGB orthomosaic",
    what: "Transform high-resolution visible images into a geometrically corrected map mosaic.",
    action: ["Request RGB orthomosaic output from the accepted DSM/camera solution.", "Record mosaic resolution, blending and NoData settings.", "Inspect seams, ghosting, boundaries, water and alignment with control."],
    where: "PIX4Dmapper → DSM, Orthomosaic and Index; then GIS/image viewer.",
    why: "RGB provides spatial context, texture, boundaries and photogrammetric detail; it is not merely a display photograph.",
    input: ["Accepted RGB camera geometry", "DSM", "RGB images"],
    output: ["RGB orthomosaic", "RGB metadata", "Seam/alignment QA"],
    check: ["Expected ≈2.7 cm/pixel project output is recorded, not confused with guaranteed effective resolution.", "No duplicate/ghosted features undermine interpretation.", "Extent covers the field evidence."],
    failure: "Investigate geometry, DSM, overlap, water/texture or blending rather than accepting a visually attractive but displaced mosaic.",
    next: "Generate calibrated Green, Red, Red Edge and NIR reflectance maps.", reference: "reference-products",
  },
  {
    number: "18", phase: "PRODUCTS", title: "Generate multispectral reflectance maps",
    what: "Create radiometrically meaningful, spatially aligned Sequoia band rasters.",
    action: ["Request Reflectance Map GeoTIFFs for Green, Red, Red Edge and NIR.", "Apply/verify the documented radiometric-calibration inputs and processing state.", "Inspect band identity, scaling, registration, masks, grid and NoData."],
    where: "PIX4Dmapper → DSM, Orthomosaic and Index → Reflectance Map; then GIS/raster QA.",
    why: "Quantitative indices require compatible reflectance bands; a display mosaic or raw digital number is not equivalent.",
    input: ["Sequoia images", "Calibration/illumination evidence", "Accepted geometry", "Band output settings"],
    output: ["Green/Red/Red Edge/NIR reflectance GeoTIFFs", "Radiometric metadata", "Band-alignment QA"],
    check: ["Bands are labelled and scaled correctly.", "Project output is ≈10 cm/pixel and grids align exactly.", "Reflectance ranges and NoData are plausible."],
    failure: "Block index calculation when calibration, scale, band identity, registration or grid compatibility is unknown.",
    next: "Process and identify the actual thermal measurement product separately.", reference: "reference-sensors",
  },
  {
    number: "19", phase: "PRODUCTS", title: "Process thermal imagery without confusing palette and measurement",
    what: "Keep Duet T RGB geometry and thermal observations conceptually and technically distinct.",
    action: ["Verify the paired S.O.D.A. RGB and 640 × 512 thermal image groups.", "Generate/open the thermal product carrying thermal values under the documented calibration workflow.", "Label apparent surface-temperature/thermal signal, units, scale and limitations."],
    where: "PIX4Dmapper Duet T workflow + thermal-product viewer/GIS.",
    why: "A thermal-looking colour ramp applied to an RGB-derived point cloud contains no thermal measurement.",
    input: ["Duet T RGB images", "Duet T thermal images", "Accepted geometry", "Thermal calibration metadata"],
    output: ["Thermal raster/product", "RGB companion product", "Thermal interpretation record"],
    check: ["The value source is the thermal sensor, not the palette.", "Expected project thermal GSD ≈15.6 cm/pixel is recorded.", "No direct soil-moisture or plant-stress claim is made without validation."],
    failure: "Do not interpret colours when the underlying values, units, calibration or source image group are unknown.",
    next: "Derive indices only from compatible reflectance bands.", reference: "reference-sensors",
  },
  {
    number: "20", phase: "PRODUCTS", title: "Calculate and audit vegetation indices",
    what: "Apply the documented project formulas to aligned, valid reflectance bands.",
    action: ["Use the verified NDVI, GNDVI, SAVI, MSAVI, RNDVI, RTVIcore, SRe and CIre formulas.", "Apply common masks/NoData and retain formula metadata.", "Inspect ranges, denominator failures and spatial artefacts."],
    where: "Reproducible raster-processing workflow after reflectance QA.",
    why: "An index compresses spectral contrast into a predictor; it is neither an observed trait nor a biodiversity measurement.",
    input: ["Aligned reflectance bands", "Verified formulas", "Common mask and grid"],
    output: ["Eight index rasters", "Formula/provenance record", "Range and mask QA"],
    check: ["RNDVI is not mislabelled NDVIRe.", "SAVI uses the documented L=0.5 form.", "Invalid/near-zero denominators are handled."],
    failure: "Return to band scaling, alignment, formula transcription or masks when ranges/patterns are implausible.",
    next: "Audit every final product as one linked evidence package.", reference: "reference-products",
  },
  {
    number: "21", phase: "HANDOFF", title: "Run final cross-product QA",
    what: "Decide whether geometry, radiometry, grids and field coverage are jointly fit for analysis.",
    action: ["Re-read the final Pix4D Quality Report and all unresolved warnings.", "Compare RGB, DSM, reflectance, thermal and index extents/grids.", "Overlay plots/control and record accept, qualify or block decisions."],
    where: "Pix4D Quality Report + GIS + project QA register.",
    why: "A set of individually readable files can still fail as a combined modelling stack.",
    input: ["Quality Reports", "All output rasters", "Control/plot geometry", "Processing log"],
    output: ["Final QA register", "Accepted product list", "Documented exclusions/limitations"],
    check: ["CRS, extent, resolution, alignment, band identity, units, masks and NoData reconcile.", "Plots fall inside accepted coverage.", "Warnings and uncertainty propagate to later modelling."],
    failure: "Exclude or reprocess the affected product; never fill a missing trait or raster value with zero merely to complete the table.",
    next: "Package accepted products and provenance for analysis.", reference: "reference-products",
  },
  {
    number: "22", phase: "HANDOFF", title: "Export an analysis-ready mission package",
    what: "Deliver accepted rasters and metadata in a structure another researcher can reproduce and interpret.",
    action: ["Archive raw, processing, output and QA directories separately.", "Write a manifest with site, date, sensor, CRS, grid, units, scaling, NoData and checksums.", "Create plot-level raster summaries using the documented spatial support before modelling."],
    where: "Project archive + reproducible GIS/Python handoff workflow.",
    why: "The next model row must be traceable to a field plot, accepted raster values and the processing decisions that created them.",
    input: ["Accepted products", "QA register", "Plot geometry/SampleID", "Processing and sensor metadata"],
    output: ["Analysis-ready raster stack", "Manifest and checksums", "Plot-level predictor table", "Handoff limitations"],
    check: ["SampleID, geometry and table keys are consistent.", "Pixel samples are aggregated to plot support rather than treated as independent field observations.", "The UAV is not claimed to directly measure species, CCI, leaf area or AGB."],
    failure: "Do not release a stack that cannot be traced to sensor, mission, CRS, calibration, grid and QA evidence.",
    next: "Model ecological responses, validate by site/space, and interpret the prediction surface within its evidence limits.", reference: "reference-field-link",
  },
];

export const uavTutorialPhases = [
  { id: "PLAN", label: "Plan", range: "01–03" },
  { id: "ACQUIRE", label: "Acquire", range: "04–05" },
  { id: "POSITION", label: "Position", range: "06–08" },
  { id: "RECONSTRUCT", label: "Reconstruct", range: "09–15" },
  { id: "PRODUCTS", label: "Products", range: "16–20" },
  { id: "HANDOFF", label: "QA + handoff", range: "21–22" },
] as const;

export const sequoiaBands = [
  { name: "Green", centre: "550 nm", bandwidth: "40 nm", className: "green", meaning: "Visible green reflectance; useful context for vegetation colour and green–NIR contrasts. Pigments, illumination, canopy and background all contribute." },
  { name: "Red", centre: "660 nm", bandwidth: "40 nm", className: "red", meaning: "A region of strong chlorophyll absorption in green vegetation and the visible term used in NDVI. It is not a direct chlorophyll reading." },
  { name: "Red Edge", centre: "735 nm", bandwidth: "10 nm", className: "rededge", meaning: "Samples the rapid transition from red absorption toward NIR reflectance. It can be sensitive to canopy and chlorophyll differences, without mapping either one-to-one." },
  { name: "NIR", centre: "790 nm", bandwidth: "40 nm", className: "nir", meaning: "Strongly influenced by leaf and canopy scattering and vegetation amount. Structure, shadows, water and background can change the signal." },
] as const;

export const flightConfiguration = [
  { system: "Multispectral", payload: "Parrot Sequoia", altitude: "106–109 m AGL", overlap: "80% forward · 75% side", gsd: "≈10 cm/pixel", role: "Green, Red, Red Edge and NIR reflectance products" },
  { system: "RGB", payload: "senseFly Duet T · S.O.D.A. RGB", altitude: "119–125 m AGL", overlap: "85–88% forward · 80–86% side", gsd: "≈2.7 cm/pixel", role: "Visible context, texture, boundaries and photogrammetric geometry" },
  { system: "Thermal", payload: "senseFly Duet T · 640 × 512 thermal", altitude: "Project mission record", overlap: "Paired Duet T acquisition", gsd: "≈15.6 cm/pixel", role: "Thermal infrared product; not reflectance" },
] as const;

export const vegetationIndices = [
  { id: "NDVI", name: "Normalized Difference Vegetation Index", formula: "(NIR − Red) / (NIR + Red)", why: "Red absorption contrasted with NIR scattering", use: "General vegetation-condition contrast", limits: "Can saturate; soil, canopy, atmosphere and shadows matter." },
  { id: "GNDVI", name: "Green Normalized Difference Vegetation Index", formula: "(NIR − Green) / (NIR + Green)", why: "Green-to-NIR contrast", use: "Complementary canopy and pigment-sensitive predictor", limits: "Does not directly measure chlorophyll or photosynthesis." },
  { id: "SAVI", name: "Soil Adjusted Vegetation Index", formula: "((NIR − Red) / (NIR + Red + 0.5)) × 1.5", why: "Adds a documented soil-adjustment term", use: "Sparse vegetation and exposed-background conditions", limits: "L = 0.5 is a parameter choice, not universal correction." },
  { id: "MSAVI", name: "Modified Soil Adjusted Vegetation Index", formula: "(2NIR + 1 − √((2NIR + 1)² − 8(NIR − Red))) / 2", why: "Adaptive red–NIR soil adjustment", use: "Complementary predictor where soil background is visible", limits: "Requires valid reflectance, masks and a non-negative radicand." },
  { id: "RNDVI", name: "Renormalized Difference Vegetation Index", formula: "(NIR − Red) / √(NIR + Red)", why: "Renormalizes the red–NIR contrast", use: "Vegetation-density sensitivity in the project predictor set", limits: "Not NDVIRe; denominator and reflectance scale must be valid." },
  { id: "RTVIcore", name: "Red-edge Triangular Vegetation Index Core", formula: "100(NIR − Red Edge) − 10(NIR − Green)", why: "Combines NIR, Red Edge and Green contrasts", use: "Red-edge-sensitive canopy/pigment predictor", limits: "Empirical relationship must be validated for this campaign." },
  { id: "SRe", name: "Red-edge Simple Ratio", formula: "NIR / Red Edge", why: "NIR-to-Red Edge ratio", use: "Canopy-condition and red-edge predictor", limits: "Unstable when the denominator is invalid or near zero." },
  { id: "CIre", name: "Red-edge Chlorophyll Index", formula: "(NIR / Red Edge) − 1", why: "Shifted red-edge simple ratio", use: "Chlorophyll-associated project predictor", limits: "An index, not a direct CCI or chlorophyll measurement." },
] as const;

export const uavOutputs = [
  ["RGB orthomosaic", "processed", "Orthorectified visible-colour mosaic", "≈2.7 cm/pixel", "Context, boundaries, texture", "Colour and texture are not species or trait measurements"],
  ["Green reflectance", "processed", "Calibrated Green-band reflectance", "≈10 cm/pixel", "Visible vegetation/background information", "Illumination and calibration quality remain consequential"],
  ["Red reflectance", "processed", "Calibrated Red-band reflectance", "≈10 cm/pixel", "Pigment-sensitive contrast; NDVI input", "Not a direct chlorophyll reading"],
  ["Red Edge reflectance", "processed", "Calibrated Red Edge reflectance", "≈10 cm/pixel", "Red-edge indices and modelling", "Sensitive to registration and calibration"],
  ["NIR reflectance", "processed", "Calibrated NIR reflectance", "≈10 cm/pixel", "Canopy/leaf scattering and indices", "Water, shadows and background can dominate"],
  ["DSM", "derived", "Elevation of the visible upper surface", "output-grid dependent", "Surface structure and height-related predictors", "DSM is not a bare-earth DEM"],
  ["Point cloud", "derived", "3-D reconstructed surface samples", "irregular 3-D support", "Geometry QA and DSM production", "Density is not accuracy"],
  ["Thermal product", "processed", "Thermal infrared signal / apparent surface temperature where calibrated", "≈15.6 cm/pixel", "Surface-temperature pattern inspection", "Not reflectance, soil moisture or plant stress directly"],
  ["Vegetation indices", "derived", "Formula applied to compatible reflectance bands", "aligned output grid", "Compact spectral predictors", "Band ≠ index; index ≠ trait"],
] as const;

export type DroneStep = {
  number: string;
  title: string;
  action: string;
  why: string;
  expected: string;
  check: string;
  stop: string;
};

export const droneSteps: DroneStep[] = [
  { number: "00", title: "Retrieve aircraft logs and camera storage", action: "Use the approved eBee X procedure. Images and basic flight data are on the camera SD card. For internal drone logs: remove the camera, power the aircraft on, wait about 20 seconds, then attach mini-USB to the computer. Keep the two retrieval paths distinct.", why: "The camera media and aircraft internal log store contain different evidence.", expected: "Readable camera media plus the required mission log files.", check: "Confirm aircraft generation, payload, supported cable and storage before access.", stop: "The hardware procedure, power state or media identity is uncertain." },
  { number: "01", title: "Copy first, process second", action: "Copy logs, RGB, multispectral, thermal and GNSS files into the project raw-data folders. Preserve the source media unchanged.", why: "A write-protected raw copy makes the workflow recoverable and auditable.", expected: "A complete raw inventory on the project drive.", check: "Compare file counts and sizes with the source media; record the copy date.", stop: "Files are missing, unreadable or being processed directly from the SD card." },
  { number: "02", title: "Start eMotion Postflight", action: "Open eMotion and choose Postflight / Flight Data Manager for the mission.", why: "Postflight associates mission logs, images, geotags and GNSS correction evidence.", expected: "A new processing project with no source files moved or renamed.", check: "Confirm the project location has sufficient space and is not the raw folder.", stop: "The selected workspace is temporary, full or inside the raw archive." },
  { number: "03", title: "Verify mission, date and time", action: "Select the flight log and record site, date, start/end and time basis. For this 2024 summer campaign, Estonia local time was UTC+3; convert deliberately before requesting base-station data.", why: "RINEX observations must overlap the complete flight interval.", expected: "One uniquely identified mission and a base-data interval with margin.", check: "Cross-check filename, log timeline, site and local/UTC conversion.", stop: "The time zone or mission identity is ambiguous." },
  { number: "04", title: "Match logs to the image folder", action: "Load the correct flight log and select the matching camera-image folder; let eMotion associate image capture times with the mission record.", why: "This creates image-to-log geotag associations; it is not photogrammetric feature matching.", expected: "The expected image count is associated with one mission.", check: "The 2024 manual normally expected 100% matching; investigate every exception.", stop: "Site/date disagree, image count is unexpected or matching is not unique." },
  { number: "05", title: "Load RINEX and process PPK", action: "Obtain observation/navigation data from the relevant approved reference station for an interval covering the flight, load the required files and run PPK.", why: "PPK combines rover and reference observations after flight to improve camera-position estimates.", expected: "Corrected camera geotags and a documented quality summary.", check: "Inspect fix status, base position, time overlap and improvement; the manual example changed from about 0.806 m standalone to 0.049 m post-processed uncertainty.", stop: "Reference station, antenna metadata, time overlap or solution quality is wrong or unknown." },
  { number: "06", title: "Export corrected mission evidence", action: "Write corrected geotags where required and retain the geoinfo, trajectory, text/KML and action log produced by the project workflow.", why: "Pix4D must ingest the corrected coordinates with traceable processing evidence.", expected: "A processed image folder and supporting metadata distinct from raw data.", check: "Confirm image count, coordinate columns, units and timestamps.", stop: "Corrected and standalone positions cannot be distinguished." },
  { number: "07", title: "Create the Pix4D project", action: "Open PIX4Dmapper and add all required corrected images. For Duet T work, include both S.O.D.A. RGB and thermal images and verify their image groups/camera models.", why: "The paired rig supplies RGB geometry and thermal observations with synchronized acquisition.", expected: "All intended images are grouped under recognized camera models.", check: "Inspect Image Properties, resolution, focal/pixel metadata and image-group counts.", stop: "Camera model, group, image count or coordinate source is wrong." },
  { number: "08", title: "Set the output and GCP CRS", action: "Set the project/GCP coordinate system to Estonian Coordinate System of 1997 (EPSG:3301) when using this study’s control and analysis data.", why: "The project’s surveyed and downstream analysis coordinates use the Estonian national grid in metres.", expected: "Images, control points and output coordinates occupy the same defensible spatial reference.", check: "Read the full CRS name, EPSG code, axis/column order, horizontal units and vertical reference.", stop: "The interface only says ‘Estonian’, an auto-detected UTM CRS remains selected, or the vertical reference is unknown." },
  { number: "09", title: "Run Initial Processing only", action: "In Processing Options, keep Initial Processing checked; uncheck Point Cloud and Mesh and DSM, Orthomosaic and Index. Start step 1 only.", why: "Initial feature matching, camera orientation and bundle adjustment establish geometry before control is marked and dense products are generated.", expected: "Calibrated images, automatic tie points, sparse reconstruction and an initial Quality Report.", check: "Inspect calibration, blocks, matching, initial positions and warnings.", stop: "Images split into unexplained blocks or calibration/matching is weak." },
  { number: "10", title: "Export approved GCPs from Trimble Access", action: "Open the relevant approved Trimble Access project/job, choose Export, select a comma-delimited CSV/TXT format, choose the required control points and write the export to controlled transfer storage.", why: "Surveyed control must enter Pix4D with identifiers, coordinates and units intact.", expected: "A documented GCP CSV from the correct job.", check: "Verify point names, coordinate fields/order, elevation, delimiter, units and CRS. Internal 2024 example job names are intentionally not published.", stop: "The job, export schema or coordinate reference is unverified." },
  { number: "11", title: "Import GCP CSV", action: "Open Project → GCP/MTP Manager, confirm EPSG:3301, choose Import GCPs, select the CSV and map the actual coordinate columns deliberately.", why: "Import declares surveyed constraints; it does not prove they are correctly identified in images.", expected: "Control points plot in plausible positions inside/around the mission.", check: "Validate X/Y/Z order, axis convention, metres, elevations and point spread.", stop: "Points plot far away, coordinate order is unclear or heights are implausible." },
  { number: "12", title: "Manually mark every GCP", action: "For each GCP, find the exact target in multiple suitable images and mark the same physical point precisely in GCP/MTP Manager or rayCloud.", why: "One surveyed point appears in several overlapping camera views; accurate image measurements constrain reprojection and bundle geometry.", expected: "Every accepted GCP has consistent marks across enough well-distributed images.", check: "Zoom, target identity, mark consistency, image geometry and residual feedback.", stop: "The target is obscured, ambiguous or repeatedly produces inconsistent reprojection." },
  { number: "13", title: "Reoptimize", action: "Choose Process → Reoptimize after GCP marking.", why: "Reoptimization updates camera and reconstruction parameters using the newly marked control constraints.", expected: "An updated solution with control integrated into the bundle adjustment.", check: "Compare residuals, camera geometry, calibration and block structure with the initial solution.", stop: "Residuals worsen, a point becomes an outlier or the model deforms." },
  { number: "14", title: "Audit GCPs and MTPs", action: "Review every control residual, suspicious mark, image observation and the spatial distribution of control; correct and reoptimize again when necessary.", why: "A low average can conceal one wrong point or a weakly controlled edge.", expected: "No unexplained outlier and defensible control coverage.", check: "Horizontal/vertical residuals, point count, mark count and spatial pattern; retain independent check points where available.", stop: "A fitted GCP is being presented as independent accuracy evidence." },
  { number: "15", title: "Enable final processing stages", action: "Uncheck Initial Processing; check Point Cloud and Mesh and DSM, Orthomosaic and Index after accepting geometry.", why: "Dense reconstruction and final rasters should build from accepted camera geometry instead of hiding an unresolved initial failure.", expected: "Only steps 2 and 3 are queued.", check: "Record the accepted step-1 report before starting.", stop: "Initial processing or control QA is still unresolved." },
  { number: "16", title: "Choose point-cloud settings", action: "Select Low/Fast for rapid diagnostic output or Optimal when the purpose and resources justify denser reconstruction.", why: "Point density trades time and detail; it does not independently set positional accuracy.", expected: "A documented setting matched to the processing purpose.", check: "Available storage/RAM, expected surface detail, noise and QA objective.", stop: "A historical setting is being copied without considering the dataset and output use." },
  { number: "17", title: "Request orthomosaic and reflectance maps", action: "Under DSM, Orthomosaic and Index, request the needed DSM/orthomosaic outputs and Reflectance Map GeoTIFFs for multispectral bands.", why: "An orthomosaic is a geometrically corrected mosaic; a reflectance map is the radiometrically meaningful band product needed for quantitative multispectral analysis.", expected: "Green, Red, Red Edge and NIR reflectance layers plus selected geometric outputs.", check: "Radiometric calibration, band labels, GeoTIFF, resolution, CRS and NoData.", stop: "A display mosaic or raw digital number is being called reflectance." },
  { number: "18", title: "Run steps 2 and 3", action: "Start Point Cloud and Mesh followed by DSM, Orthomosaic and Index from the accepted step-1/GCP state.", why: "Dense surface reconstruction supplies geometry used by the DSM and orthorectification.", expected: "Point cloud, DSM, orthomosaic and requested reflectance products.", check: "Processing completes without unresolved warnings and outputs open independently.", stop: "The project silently reruns/overwrites an unarchived earlier stage or a stage fails." },
  { number: "19", title: "Read the Quality Report", action: "Review calibration, image matching, geolocation, overlap, GCP residuals, camera model changes, reconstruction warnings and output previews.", why: "‘Completed’ reports software execution, not scientific validity.", expected: "A signed-off QA record with limitations and follow-up actions.", check: "All images/blocks, overlap holes, residual distributions, output CRS and warnings.", stop: "A warning is unexplained or the report is missing." },
  { number: "20", title: "Inventory and archive outputs", action: "Open every requested product, record metadata/checksums and archive the raw, processing, output and QA folders separately.", why: "A reproducible handoff needs readable products plus provenance, not a Pix4D project alone.", expected: "RGB, multispectral, structural and thermal outputs are labelled by measurement type and use.", check: "CRS, grid, resolution, band identity, units, masks, NoData, extent, timestamps and QA linkage.", stop: "A product cannot be traced to its sensor, mission and processing settings." },
];

export const qaStopGates = [
  "Wrong mission or unexplained image count",
  "Wrong UTC/local-time conversion or incomplete RINEX interval",
  "Weak or undocumented PPK solution",
  "Image/log association failure",
  "Wrong camera model or image group",
  "Wrong or ambiguous CRS/vertical reference",
  "Unverified radiometric calibration",
  "Insufficient achieved overlap or motion blur",
  "Seamlines, ghosting or water matching failure",
  "Band misregistration or mismatched raster grids",
  "NoData or scaling ambiguity",
  "Field plots outside accepted coverage",
] as const;

export const operationalChecklist = [
  "Copy logs and all sensor imagery",
  "Preserve raw data",
  "Start eMotion Postflight",
  "Verify mission, date, UTC/local-time conversion and image count",
  "Load the correct logs and image folder",
  "Load PPK/RINEX and verify the solution",
  "Export corrected imagery and processing evidence",
  "Start Pix4D and add the required camera groups",
  "Verify camera model and EPSG:3301 where applicable",
  "Run Initial Processing only",
  "Export/import GCP CSV if control is used",
  "Mark every GCP and reoptimize",
  "Inspect residuals, distribution and Quality Report",
  "Run Point Cloud and Mesh",
  "Run DSM, Orthomosaic and Index",
  "Generate and verify reflectance maps",
  "Archive products, metadata and QA",
] as const;
