import type { Metadata } from "next";
import { HyperspectralLeakageLab, SpectralExplorer, SpectralMixer } from "@/app/components/hyperspectral-field-lab-interactions";
import { JsonLd, SeoBreadcrumbs, SeoFooter, SeoHeader } from "@/app/components/seo-navigation";
import { hyperspectralFieldLabPath, hyperspectralFieldLabSources, hyperspectralWorkflowSteps } from "@/lib/hyperspectral-field-lab";
import { creatorReference } from "@/lib/professional-identity";
import { academyAssetUrl, academyHref, academyUrl } from "@/lib/site-paths";

const url = academyUrl(hyperspectralFieldLabPath);
export const metadata: Metadata = { title: "Field Lab 10 · Hyperspectral Signatures | Remote Sensing Scientist Academy", description: "Audit a hyperspectral cube, mask invalid evidence, link spectra to reference samples and validate a leakage-safe mapping workflow.", alternates: { canonical: url }, openGraph: { title: "Field Lab 10 · Hyperspectral Signatures", description: "Spectral cube to validated map, without automatic identification claims.", type: "article", url, images: [{ url: academyAssetUrl("/og.png"), width: 1536, height: 1024, alt: "Remote Sensing Scientist Academy" }] } };

export default function HyperspectralFieldLabPage() { return <><JsonLd value={{ "@context": "https://schema.org", "@type": "LearningResource", name: "Field Lab 10 · Hyperspectral Signatures", description: metadata.description, url, learningResourceType: "Field lab", educationalUse: "instruction", creator: creatorReference() }} /><SeoHeader current="field-labs" /><main className="hyperspectral-field-lab" id="main-content"><SeoBreadcrumbs items={[{ label: "Academy", href: academyHref("/") }, { label: "Field Labs", href: academyHref("/field-labs/") }, { label: "Hyperspectral signatures" }]} />
  <header className="hyper-lab-hero"><div><p className="section-kicker">Field Lab 10 · Imaging spectroscopy</p><h1>Read a spectral cube without turning a curve into an identity</h1><p>Move from wavelength metadata and bad-band QA to reference-linked spectra, fold-safe feature engineering, spatial validation and a qualified prediction map.</p><div><a href="#hyper-workflow">Start the workflow</a><a href={academyHref("/module-2/hyperspectral-remote-sensing/")}>Review hyperspectral foundations</a></div></div><aside><span>A CUBE HAS THREE AXES</span><div><b>x</b><b>y</b><b>λ</b></div><p>Every pixel contains a sampled spectrum; every band is still an image. Neither view removes mixtures, noise or validation needs.</p></aside></header>
  <section className="hyper-scope"><strong>Lab evidence boundary</strong><p>The included 20-band signatures are sparse synthetic teaching curves—not a real contiguous hyperspectral cube, not species-identification evidence and not measurements from the 2024 Estonia campaign.</p></section>
  <section className="hyper-foundation"><div><p className="section-kicker">Measurement chain</p><h2>Radiance → correction → reflectance → features → model</h2><p>Imaging spectrometers sample spectral radiance across many narrow bands. Reflectance requires calibration and atmospheric/illumination treatment. Features, endmembers and predictions are later analytical products.</p></div><div className="hyper-chain">{["RADIANCE CUBE", "SURFACE / ATMOSPHERIC MODEL", "REFLECTANCE CUBE", "VALID BANDS + PIXELS", "FEATURE PIPELINE", "PREDICTION + UNCERTAINTY"].map((item, index) => <span key={item}><i>{String(index + 1).padStart(2, "0")}</i>{item}</span>)}</div><aside><b>AVIRIS example—not a universal specification</b><p>NASA’s AVIRIS-Classic records calibrated upwelling spectral radiance in 224 contiguous channels from 400 to 2500 nm. Other instruments have different wavelength ranges, bandwidths, response functions and quality flags.</p></aside></section>
  <SpectralExplorer /><SpectralMixer />
  <section className="hyper-workflow" id="hyper-workflow" aria-labelledby="hyper-workflow-title"><header><p className="section-kicker">End-to-end procedure</p><h2 id="hyper-workflow-title">Question → cube → valid spectra → model → qualified map</h2><p>High spectral dimensionality adds information and extra ways to leak, overfit or misread it. Stop when an upstream contract is unresolved.</p></header><nav aria-label="Hyperspectral workflow">{hyperspectralWorkflowSteps.map((step) => <a href={`#hyper-step-${step.n}`} key={step.n}><span>{step.n}</span>{step.phase}</a>)}</nav><div>{hyperspectralWorkflowSteps.map((step) => <article id={`hyper-step-${step.n}`} key={step.n}><header><span>{step.n} · {step.phase}</span><h3>{step.title}</h3></header><section><div><h4>ACTION</h4><ol>{step.action.map((item) => <li key={item}>{item}</li>)}</ol></div><div><h4>CHECK</h4><ul>{step.check.map((item) => <li key={item}>{item}</li>)}</ul></div><div><h4>OUTPUT</h4><p>{step.output}</p><aside><b>IF THIS FAILS</b><p>{step.fail}</p></aside></div></section></article>)}</div></section>
  <HyperspectralLeakageLab />
  <section className="hyper-products"><header><p className="section-kicker">Analysis-ready handoff</p><h2>The class map is the end of a chain, not the whole result</h2></header><div>{[["SOURCE", "Cube identifiers, wavelengths, bandwidths, units and scale"], ["VALIDITY", "Pixel mask, band mask, SNR/quality record and exclusions"], ["REFERENCE", "Labels, support, timing, folds and spectral extraction table"], ["MODEL", "Fitted preprocessing, features, estimator and selection record"], ["OUTPUT", "Prediction, uncertainty, applicability and validation evidence"]].map(([label, text]) => <article key={label}><span>{label}</span><p>{text}</p></article>)}</div><aside><b>Supported:</b> validated class or response predictions within the stated sensor, sampling and application domain.<br /><b>Not automatic:</b> species identity, chemical concentration, stress cause or transfer to another date/sensor/site.</aside></section>
  <section className="hyper-downloads"><div><p className="section-kicker">Workstation pack</p><h2>Download the spectral audit</h2><p>The table is synthetic, intentionally sparse and includes four flagged bands.</p></div><div><a href={academyAssetUrl("/lesson-resources/module-2/satellite-eo/hyperspectral_signatures.csv")} download>Synthetic spectral signatures · CSV</a><a href={academyAssetUrl("/field-labs/hyperspectral-signatures/hyperspectral-evidence-checklist.md")} download>Hyperspectral evidence checklist · Markdown</a></div></section>
  <section className="hyper-references"><p className="section-kicker">Authoritative references</p><h2>Instrument, validation and spectral-library guidance</h2><ul><li><a href={hyperspectralFieldLabSources.aviris} target="_blank" rel="noopener noreferrer">NASA JPL AVIRIS instrument overview ↗</a></li><li><a href={hyperspectralFieldLabSources.neonIntro} target="_blank" rel="noopener noreferrer">NSF NEON cube, wavelength and bad-band tutorial ↗</a></li><li><a href={hyperspectralFieldLabSources.neonValidation} target="_blank" rel="noopener noreferrer">NSF NEON spectrometer validation and uncertainty ↗</a></li><li><a href={hyperspectralFieldLabSources.usgsLibrary} target="_blank" rel="noopener noreferrer">USGS Spectral Library and sample documentation ↗</a></li></ul></section>
  </main><SeoFooter /></>; }
