import type { Metadata } from "next";
import { LandsatScaleLab, ThermalClaimCheck, ThermalSignalLab } from "@/app/components/thermal-lesson-interactions";
import { JsonLd, SeoBreadcrumbs, SeoFooter, SeoHeader } from "@/app/components/seo-navigation";
import { advancedThermalLessonPath, advancedThermalSources, thermalWorkflowSteps } from "@/lib/advanced-thermal-lesson";
import { creatorReference } from "@/lib/professional-identity";
import { academyAssetUrl, academyHref, academyUrl } from "@/lib/site-paths";

const url = academyUrl(advancedThermalLessonPath);
export const metadata: Metadata = {
  title: "Advanced Thermal Remote Sensing | Remote Sensing Scientist Academy",
  description: "Trace thermal radiance through emissivity, atmosphere, temperature retrieval, QA, validation and defensible ecological interpretation.",
  alternates: { canonical: url },
  openGraph: { title: "Advanced Thermal Remote Sensing", description: "From emitted radiance to a validated surface-temperature claim.", type: "article", url, images: [{ url: academyAssetUrl("/og.png"), width: 1536, height: 1024, alt: "Remote Sensing Scientist Academy" }] },
};

const terms = [
  ["STORED VALUE", "Integer delivered for efficient storage", "Decode with product scale, offset, fill and valid range."],
  ["AT-SENSOR RADIANCE", "Thermal energy reaching the detector", "Contains surface emission plus atmospheric and reflected contributions."],
  ["BRIGHTNESS TEMPERATURE", "Blackbody-equivalent temperature inferred from radiance", "Not land-surface temperature unless emissivity and atmosphere are addressed."],
  ["LAND-SURFACE TEMPERATURE", "Retrieved radiometric skin temperature of the observed surface", "Not the standard near-surface air temperature in a weather report."],
  ["ECOLOGICAL MODEL OUTPUT", "Stress, ET or another response estimated using thermal and supporting evidence", "Modelled—not directly measured by the thermal band."],
] as const;

const comparisons = [
  { source: "LANDSAT COLLECTION 2 L2", measure: "Surface temperature in Kelvin after decoding", support: "Scene product; inspect native thermal/product support and grid", strength: "Long, consistently processed archive", caution: "Single-channel retrieval uses emissivity and atmospheric auxiliary data; cloud-adjacent errors and emissivity gaps/issues remain." },
  { source: "ECOSTRESS L2 LSTE", measure: "Land-surface temperature and emissivity retrieved across five active TIR bands", support: "Swath or 70 m gridded/tiled products", strength: "Different overpass times from the ISS support diurnal investigations", caution: "Use product cloud/quality information and current collection documentation; a 70 m pixel is a mixed surface." },
  { source: "UAV THERMAL", measure: "Sensor-specific radiance or apparent-temperature-related imagery", support: "Fine nominal pixels within a flight footprint", strength: "Local detail and flexible campaign timing", caution: "Calibration, emissivity, atmosphere, drift, viewing geometry and ground validation do not disappear at fine resolution." },
] as const;

export default function AdvancedThermalLessonPage() {
  return <><JsonLd value={{ "@context": "https://schema.org", "@type": "LearningResource", name: "Advanced Thermal Remote Sensing", description: metadata.description, url, learningResourceType: "Advanced lesson", educationalUse: "instruction", creator: creatorReference() }} /><SeoHeader /><main className="advanced-thermal-lesson" id="main-content"><SeoBreadcrumbs items={[{ label: "Academy", href: academyHref("/") }, { label: "Remote Sensing", href: `${academyHref("/")}#thermal` }, { label: "Advanced thermal remote sensing" }]} />
    <header className="thermal-lesson-hero"><div><p className="section-kicker">Standalone advanced lesson · Thermal infrared</p><h1>From emitted radiance to a defensible surface-temperature claim</h1><p>Separate what the detector receives from what a product retrieves—then carry emissivity, atmosphere, time, spatial support and validation into every ecological interpretation.</p><div><a href="#thermal-workflow">Start the evidence workflow</a><a href={academyHref("/field-labs/uav-coastal-wetlands/")}>Connect to UAV Field Lab 07</a></div></div><aside><span>THE CORE DISTINCTION</span><b>THERMAL RADIANCE</b><i>is measured at the detector</i><b>SURFACE TEMPERATURE</b><i>is retrieved under assumptions</i><b>STRESS OR ET</b><i>is a later modelled interpretation</i></aside></header>

    <section className="thermal-boundary"><strong>Evidence boundary</strong><p>This lesson uses an official Landsat decoding example and clearly labelled synthetic teaching records. It does not reproduce a real heat event, diagnose vegetation stress, or provide a universal calibration for satellite or UAV sensors.</p></section>

    <section className="thermal-physics"><div><p className="section-kicker">Measurement physics</p><h2>A thermal pixel is an energy balance observed through an atmosphere</h2><p>In the thermal infrared, the surface emits energy according to temperature and emissivity. It can also reflect downwelling atmospheric radiance. The atmosphere transmits part of the surface-leaving signal and adds path radiance before the detector records it.</p><blockquote>L<sub>sensor</sub> = τ[εB(T<sub>s</sub>) + (1−ε)L↓] + L↑</blockquote><p>This conceptual radiative-transfer relation names the dependencies; operational retrievals use sensor response functions, calibrated radiance and product-specific algorithms.</p></div><div className="thermal-energy-diagram" role="img" aria-label="Surface and atmosphere thermal radiance pathway"><span className="thermal-space">SENSOR · L<sub>sensor</sub></span><i className="thermal-up">L↑ atmosphere</i><i className="thermal-transmit">τ transmission</i><span className="thermal-atmosphere">ATMOSPHERE</span><b className="thermal-emission">εB(T<sub>s</sub>) emission ↑</b><b className="thermal-down">L↓ reflected by surface ↕</b><span className="thermal-surface">SURFACE · T<sub>s</sub> · ε</span></div></section>

    <section className="thermal-terms"><header><p className="section-kicker">Do not collapse the processing ladder</p><h2>Five quantities that answer different questions</h2></header><div>{terms.map(([label, meaning, rule], index) => <article key={label}><span>{String(index + 1).padStart(2, "0")}</span><h3>{label}</h3><p>{meaning}</p><aside>{rule}</aside></article>)}</div></section>

    <ThermalSignalLab />

    <section className="thermal-products"><header><p className="section-kicker">Choose by question and product—not by colour</p><h2>Satellite and UAV thermal evidence have different support</h2></header><div role="table" aria-label="Thermal product comparison"><div role="row" className="thermal-products-head"><span role="columnheader">SOURCE</span><span role="columnheader">WHAT THE PRODUCT REPRESENTS</span><span role="columnheader">SUPPORT</span><span role="columnheader">VALUE</span><span role="columnheader">LIMIT</span></div>{comparisons.map((item) => <article role="row" key={item.source}><b role="cell">{item.source}</b><p role="cell">{item.measure}</p><p role="cell">{item.support}</p><p role="cell">{item.strength}</p><p role="cell">{item.caution}</p></article>)}</div><aside><strong>PIXEL SIZE ≠ THERMAL DETAIL</strong><p>Native sampling, optical response, geolocation, resampling and mixed surfaces all influence effective spatial support. An upsampled raster has more cells—not new thermal observations.</p></aside></section>

    <LandsatScaleLab />

    <section className="thermal-workflow" id="thermal-workflow" aria-labelledby="thermal-workflow-title"><header><p className="section-kicker">End-to-end procedure</p><h2 id="thermal-workflow-title">Question → radiance/product → valid temperature → qualified inference</h2><p>Each gate protects the next. A beautiful heat map cannot repair a product-level, emissivity, cloud, timing or validation failure.</p></header><nav aria-label="Advanced thermal workflow">{thermalWorkflowSteps.map((step) => <a href={`#thermal-step-${step.n}`} key={step.n}><span>{step.n}</span>{step.phase}</a>)}</nav><div>{thermalWorkflowSteps.map((step) => <article id={`thermal-step-${step.n}`} key={step.n}><header><span>{step.n} · {step.phase}</span><h3>{step.title}</h3></header><section><div><h4>ACTION</h4><ol>{step.action.map((item) => <li key={item}>{item}</li>)}</ol></div><div><h4>CHECK</h4><ul>{step.check.map((item) => <li key={item}>{item}</li>)}</ul></div><div><h4>OUTPUT</h4><p>{step.output}</p><aside><b>IF THIS FAILS</b><p>{step.fail}</p></aside></div></section></article>)}</div></section>

    <section className="thermal-time"><div><p className="section-kicker">Time is part of the measurement</p><h2>The same place can tell a different thermal story through one day</h2><p>Incoming radiation, shading, wind, evaporation and thermal inertia change the surface energy balance. Comparisons must carry acquisition time and recent conditions.</p></div><div className="thermal-timeline" role="img" aria-label="Conceptual diurnal surface temperature curve"><svg viewBox="0 0 800 270"><title>Conceptual diurnal surface temperature curve</title><path d="M48 220H770M48 30V220" /><path className="thermal-curve" d="M48 190 C150 205 185 150 260 92 S420 44 510 88 S650 180 770 196" /><line x1="286" x2="286" y1="45" y2="220" /><line x1="600" x2="600" y1="45" y2="220" /><text x="42" y="245">SUNRISE</text><text x="250" y="245">MORNING</text><text x="455" y="245">AFTERNOON</text><text x="680" y="245">NIGHT</text></svg><aside><b>Conceptual only</b><p>The curve is not a universal daily cycle. Surface material, water availability, weather, season and geometry change its timing and amplitude.</p></aside></div></section>

    <ThermalClaimCheck />

    <section className="thermal-interpretation"><header><p className="section-kicker">Ecological interpretation ladder</p><h2>Add evidence before climbing from temperature to process</h2></header><div>{[["OBSERVED / RETRIEVED", "Valid radiance, brightness temperature or land-surface temperature at a stated time and support."], ["DERIVED", "Anomaly, contrast, zonal summary or time-series feature calculated with explicit masks and context."], ["MODELLED", "Evapotranspiration, water stress, habitat response or hazard class estimated with supporting predictors and validation."], ["INTERPRETED", "A process explanation that remains conditional on design, alternatives, uncertainty and domain knowledge."]].map(([label, text]) => <article key={label}><span>{label}</span><p>{text}</p></article>)}</div><blockquote>LAND-SURFACE TEMPERATURE ≠ AIR TEMPERATURE<br />WARMER ≠ AUTOMATICALLY DRIER OR STRESSED<br />A THERMAL PALETTE ≠ A THERMAL MEASUREMENT</blockquote></section>

    <section className="thermal-handoff"><div><p className="section-kicker">Analysis-ready handoff</p><h2>Release the evidence, not only the heat map</h2><p>A defensible package keeps the source product, scale/offset, QA, masks, emissivity/atmospheric context, acquisition metadata, validation and limitations attached to the temperature values.</p></div><div><a href={academyAssetUrl("/lessons/advanced-thermal/synthetic-thermal-pixel-audit.csv")} download>Synthetic thermal pixel audit · CSV</a><a href={academyAssetUrl("/lessons/advanced-thermal/thermal-evidence-checklist.md")} download>Thermal evidence checklist · Markdown</a></div></section>

    <section className="thermal-references"><p className="section-kicker">Authoritative references</p><h2>Product physics, scale and current documentation</h2><ul><li><a href={advancedThermalSources.landsatSurfaceTemperature} target="_blank" rel="noopener noreferrer">USGS · Landsat Collection 2 Surface Temperature ↗</a></li><li><a href={advancedThermalSources.landsatScale} target="_blank" rel="noopener noreferrer">USGS · Level-2 scale-factor guidance ↗</a></li><li><a href={advancedThermalSources.landsatLevelTwo} target="_blank" rel="noopener noreferrer">USGS · Collection 2 Level-2 science products ↗</a></li><li><a href={advancedThermalSources.ecostressProducts} target="_blank" rel="noopener noreferrer">NASA/JPL · ECOSTRESS product and algorithm guide ↗</a></li><li><a href={advancedThermalSources.ecostressMission} target="_blank" rel="noopener noreferrer">NASA/JPL · ECOSTRESS mission and instrument ↗</a></li></ul></section>
  </main><SeoFooter /></>;
}
